[pytest]

addopts = -v --tb=short -n auto

testpaths = tests

python_files = test_*.py

python_classes = Test*

python_functions = test_*

markers =
    smoke: smoke tests
    regression: regression tests
    login: login related tests
    register: register related tests
    positive: positive test cases
    negative: negative test cases